### ISSUE TITLE
Support overarching OAuth provider

### ISSUE THREAD

**Issue by erlend-sh** [kitsune-soc/kitsune#123]
Say I wanna bundle Kitsune together with some other app-servers as part of a omg.lol-like service.

For this type of hydra-service, a unified login is necessary. The best open source provider of that atm seems to be https://www.ory.sh — They also have an actively (auto-)updated [Rust client](https://github.com/ory/client-rust).

So that as a user, I’d just sign up on Weird.one and once signed up I would already have accounts on Revolt-net, Kitsune-net etc.

Related:
- #2 
- https://github.com/commune-os/weird-rs/issues/8
- https://github.com/authifier/authifier/issues/35
- https://github.com/revoltchat/revolt/discussions/103

**Comment by aumetra** [comment]
Another reason why I'm interested in this is to support existing setups some people who self-host multiple services might have set up for themselves.  
They might have an SSO solution set up to manage the logins in a central way, so updating emails or passwords or 2FA isn't such a hassle.
