### ISSUE TITLE
Follow requests

### ISSUE THREAD

**Issue by aumetra** [kitsune-soc/kitsune#184]
The basic infrastructure is already there, now we just need to add the Mastodon API endpoint for it (and add the delivery of rejects)

**Comment by aumetra** [comment]
Mastodon API documentation: https://docs.joinmastodon.org/methods/follow_requests/  

Since we already have to implement `Link` headers, we should probably put the encoding logic into a separate function (because theoretically timelines should also have these headers, they just aren't used a lot).

Also don't worry about the equivalent GraphQL function, the whole API is lacking in functionality at the moment since I mainly focussed on the Mastodon API.  
This functionality will just join the rest under a separate task of "getting the GraphQL API up to speed with the Mastodon API"

**Comment by Zeerooth** [comment]
I'll have a shot at this feature, because I see that it's not yet implemented
