### ISSUE TITLE
Registration form input field's text have wrong colour

### ISSUE THREAD

**Issue by perillamint** [kitsune-soc/kitsune#203]
## Problem

![image](https://user-images.githubusercontent.com/1622360/237013122-0cad4910-1a81-41cb-ba93-381d2fb424a1.png)

In the current welcome screen, the register form's input field does not have a proper colour and falls back to the default (usually black) colour configuration.

In most cases, this makes it extremely hard for users to interact with the registration form.

## Proposed fix
Add font colour attribute on CSS style to make it use white colour to match other texts in the screen.

**Comment by aumetra** [comment]
Closed with merge of #204
