### ISSUE TITLE
Add compatibility with an exif remover tool of some kind.

### ISSUE THREAD

**Issue by SlimeyIceCream** [kitsune-soc/kitsune#263]
I'm not sure if this is being done already, and please tell me if it is, but anyway.
Please add compatibility with an exif remover tool. A lot of people forget to remove exif data when sending messages online, many people dont even know about it. Most modern phones tag photos with location data stored in exif data, which allows anyone to find your exact location if you dont scrub it.

Example:
The pleroma [from source install](https://docs-develop.pleroma.social/backend/installation/debian_based_en/) has exiftool as an optional dependency. If it's installed then during config generation for pleroma it asks if you want to setup exiftool to automatically remove exif data.

**Comment by aumetra** [comment]
Definitely. I had this planned but hit the problem that there was no existing Rust-native solution, and because I didn't want to block the feature of uploads with me pondering about what to do.

This is definitely important to track

**Comment by SlimeyIceCream** [comment]
> Definitely. I had this planned but hit the problem that there was no existing Rust-native solution, and because I didn't want to block the feature of uploads with me pondering about what to do.
> 
> This is definitely important to track

Both of these are pretty old but maybe they might be useful? Or maybe you could make an exif remover based off of them: https://github.com/jae1911/exiftool-rs and this other one which is less old https://github.com/kamadak/exif-rs which might be a bit more useful
