### ISSUE TITLE
Update the documentation with the toml config format

### ISSUE THREAD

**Issue by Zeerooth** [kitsune-soc/kitsune#281]
Recently, in https://github.com/kitsune-soc/kitsune/pull/271 the config format has been changed to toml, yet [in the docs](https://docs.joinkitsune.org/en/running/basic-configuration/) dhall is still shown everywhere. The docs should be updated.

**Comment by aumetra** [comment]
Finally fixed up the docs. Fixed this over in the docs repo: https://github.com/kitsune-soc/docs/issues/16
