### ISSUE TITLE
Move services into `kitsune-core` crate

### ISSUE THREAD

**Issue by aumetra** [kitsune-soc/kitsune#312]
## Reasoning

We have our CLI as a dedicated binary project but we want to have things like user creation, user deletion, etc. inside the CLI, too.

Right now we would need to duplicate logic inside the CLI crate.

Another reason for moving this out is a future separate project called `kitsune-worker`. This project would be a headless job runner, enabling easy horizontal scaling by just spinning up multiple instances of that worker binary.

## Proposal

All the services and their required utility functions get moved to a new crate called `kitsune-core`.
This crate can then be used inside the `kitsune-cli` project to call things like the `UserService` or `PostService`.

**Comment by aumetra** [comment]
@Zeerooth does this sound like something reasonable to you?

**Comment by Zeerooth** [comment]
Yes, this honestly sounds like a good idea and I endorse it, especially scaling workers are going to be crucial for larger deployments. 

One alternative approach I've seen though is that some projects drop the CLI altogether (like matrix synapse) and require the admins to directly call their API to perform admin tasks (with a possibility of having different 3rd party apps as an interface), but having a CLI is always a great feature and I personally like having a fully fledged CLI. It's just more of a question if it's something that won't take too long to be justifiable in doing (for now) if API is going to have the same capabilities.

**Comment by aumetra** [comment]
Since Kitsune is still very much in flux, especially with its featureset and configurability, I would say that a CLI is probably the way forward for now.

It's conceptually simpler to implement than an API and a client for that API. That doesn't exclude the possibility of an API in the future since that would be a lot more user friendly, especially for managed instances.
