### ISSUE TITLE
Replace allocator with `mimalloc`

### ISSUE THREAD

**Issue by aumetra** [kitsune-soc/kitsune#323]
We originally used mimalloc as the allocator for Kitsune and the search service via the `mimalloc` crate and then switched to jemalloc as kind of a band-aid fix for unsoundness inside the `mimalloc` crate (they return wrongly aligned pointers. Big no no.)

There is the [`mimalloc-rust`](https://crates.io/crates/mimalloc-rust) crate though which provides bindings that are actually sound.

I personally prefer mimalloc over jemalloc since it's smaller, faster to build, and (according to their [benchmarks](https://github.com/microsoft/mimalloc/tree/master/doc/bench-2021)) outperforms a lot of other allocators.

Right now we spend ~40-50sec of our total build time on building jemalloc. We can probably reduce that with mimalloc.

**Comment by erlend-sh** [comment]
Has an issue about the unsoundness been raised in `mimalloc`? It appears to be more regularly updated.

**Comment by aumetra** [comment]
Yes, the issue is here: https://github.com/purpleprotocol/mimalloc_rust/issues/96

Didn't seem to have gotten much attention from the maintainers though

**Comment by aumetra** [comment]
I'm just doing some little PRs on the `mimalloc-rust` crate right now. Their code seems largely fine, just a few small things here and there.

And I'm looking into just upgrading it to v2.x since version 2 brings improvements in memory usage and fragmentation (according to the mimalloc README)

**Comment by aumetra** [comment]
I just read through the issue again, apparently it's just an issue with the `mimalloc` crate when compiled with the secure feature?  
That sounds a bit weird. I didn't think page protections, layout randomizations, etc. could cause unaligned pointers..
