### ISSUE TITLE
Failed to connect to and migrate the database

### ISSUE THREAD

**Issue by Lastorder-DC** [kitsune-soc/kitsune#334]
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                           ┃
┃  ██╗  ██╗██╗████████╗███████╗██╗   ██╗███╗   ██╗███████╗  ┃
┃  ██║ ██╔╝██║╚══██╔══╝██╔════╝██║   ██║████╗  ██║██╔════╝  ┃
┃  █████╔╝ ██║   ██║   ███████╗██║   ██║██╔██╗ ██║█████╗    ┃
┃  ██╔═██╗ ██║   ██║   ╚════██║██║   ██║██║╚██╗██║██╔══╝    ┃
┃  ██║  ██╗██║   ██║   ███████║╚██████╔╝██║ ╚████║███████╗  ┃
┃  ╚═╝  ╚═╝╚═╝   ╚═╝   ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝  ┃
┃                                                           ┃
┃            ActivityPub-federated microblogging            ┃
┃                                                           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

2023-09-02T12:29:21.761685Z  INFO tokio_postgres::connection: NOTICE: relation "__diesel_schema_migrations" already exists, skipping
Error:
   0: Failed to connect to and migrate the database
   1: type "language_iso_code" does not exist

Location:
   kitsune/src/main.rs:153

Suggestion: Your connection string has the correct syntax. Is the host up?

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

And no, My host is up and running fine.

```
user@host:~/kitsune$ pg_isready -d "postgres://kitsune:maskedpw@localhost:5432/kitsune"
localhost:5432 - accepting connections
user@host:~/kitsune$ psql "postgres://kitsune:maskedpw@localhost:5432/kitsune" -c "SELECT 1"
 ?column?
----------
        1
(1 row)
```

**Comment by aumetra** [comment]
Is this an older installation you are attempting to upgrade to the newest release?

**Comment by aumetra** [comment]
Okay, so, if this is an old installation you want to upgrade to the newest cut release tag, you have to do some changes yourself. Namely the following:

- Run `CREATE TYPE language_iso_code AS ENUM ();`
- Run `CREATE FUNCTION iso_code_to_language (language_iso_code)
    RETURNS regconfig
    AS $$
        SELECT 'english'::regconfig
    $$
    LANGUAGE SQL IMMUTABLE;`
- Drop the columns `display_name_ts`, `note_ts`, `username_ts` on the `accounts` table
- Drop the columns `subject_ts` and `content_ts` on the `posts` table
- Create a new non-nullable row of with the name `content_lang` of type `language_iso_code` on the `posts` table
- Create a row called `post_ts` on the `posts` table with the following properties:
```sql
    post_ts TSVECTOR GENERATED ALWAYS AS (
        to_tsvector(iso_code_to_language(content_lang), COALESCE(subject, ''))
            || to_tsvector(iso_code_to_language(content_lang), content)
    ) STORED NOT NULL,
```

- Create a row called `account_ts` on the `accounts` table with the following properties:

```sql
    account_ts TSVECTOR GENERATED ALWAYS AS (
        setweight(
            to_tsvector('simple', COALESCE(display_name, ''))
                || to_tsvector('simple', username),
            'A'
        )
            || setweight(to_tsvector('simple', COALESCE(note, '')), 'B')
    ) STORED NOT NULL,
```

The easier solution, unless you are already somewhat decently federated, is just to replace the database. 

As mentioned in the release notes:

> This release has incompatible database changes to the previous release.
Until we publish a full first alpha, we reserve us the right to continue making these kinds of breaking changes.

We are still in the "preview release" phase, where we just release things to show off what Kitsune will one day be. We haven't reached the real alpha stage yet where we guarantee database migration stability (to a certain degree).

**Comment by Lastorder-DC** [comment]
My server was not federated at all, so If that case, I choose to replace the db.
Thanks for answer, btw.
