### ISSUE TITLE
TOML parse error: missing field `allow-non-ascii-usernames`

### ISSUE THREAD

**Issue by phocks** [kitsune-soc/kitsune#430]
Just letting you know I tried a basic setup and got this error:

```
Error: 
   0: TOML parse error at line 8, column 1
   0:   |
   0: 8 | [instance]
   0:   | ^^^^^^^^^^
   0: missing field `allow-non-ascii-usernames`
   0:
```

Might be useful to add this option to the basic toml config here. https://joinkitsune.org/book/running/basic-configuration.html

**Comment by aumetra** [comment]
The changes should auto-deploy in a few minutes
