### ISSUE TITLE
Move frontend from raw VueJS to Nuxt

### ISSUE THREAD

**Issue by aumetra** [kitsune-soc/kitsune#443]
This gives us a well defined folder structure, file-based routing, and some SSG (and optional SSR capabilities)

**Comment by aumetra** [comment]
Even though a full Rust frontend would also be nice..

@Zeerooth did you ever get around to experimenting with Leptos and similar frameworks?

**Comment by Zeerooth** [comment]
Hey, I pushed the work that I've done some time ago to https://github.com/Zeerooth/kitsune/tree/experimental-frontend

This code is functional, you can use it as an example, but atm doesn't compile and emits a lot of warnings but fixing these probably wouldn't be much of a problem.

I decided to use dioxus in the end as I've discovered a nice way to integrate it into axum using liveview and then port it into desktop and mobile. Also I found that things like scopes, rendering tags etc. are more sane and coherent in dioxus than in leptos.

For the graphql part there I decided to go with cynic and it's quite an ok experience, but you have to generate your mutations, queries etc. by hand (there is a generator though).

**Comment by aumetra** [comment]
> Hey, I pushed the work that I've done some time ago to https://github.com/Zeerooth/kitsune/tree/experimental-frontend

Thanks for that! I will take a look at it and maybe write an experimental port of the rest of the UI.  
Right now we are at a good state for a port because the frontend isn't really *far* yet.
