### ISSUE TITLE
Failed to connect to and migrate the database

### ISSUE THREAD

**Issue by yonas** [kitsune-soc/kitsune#452]
```
$ kitsune --config kitsune.toml
Error:   × Failed to connect to and migrate the database                                                                                                                                                             
  help: Your connection string has the correct syntax. Is the host up?    
```

Basic sanity check:

```
$ sudo -u postgres psql -d "postgresql://kitsune@localhost/kitsune" -c "select now()"
              now              
-------------------------------
 2023-12-13 15:37:48.283756-05
(1 row)
```

config: unmodified [config.example.toml](https://github.com/kitsune-soc/kitsune/blob/main/config.example.toml)

OS: `FreeBSD 14`
database: `PostgreSQL 15.5`

**Comment by aumetra** [comment]
Okay, hang on, I gotta improve the damn error messages first 😭   
What was I thinking when I only output the `Display` impl instead of the backtrace

**Comment by aumetra** [comment]
Sorry for the delay. As soon as #454 is merged on `main`, you could attempt to rebuild and run it again.  
This time you should see the full error backtrace.

**Comment by aumetra** [comment]
And it's merged. Feel free to try it again with the latest revision.

**Comment by yonas** [comment]
Thanks! It turned out to be an issue with connection permissions. After following https://wiki.freebsd.org/PostgreSQL/Setup , the error is resolved.

On second start, all I see is an info log:

`tokio_postgres::connection: NOTICE: relation "__diesel_schema_migrations" already exists, skipping`
