### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by kaido2ki** [kitsune-soc/kitsune#609]
hi, I'm brand new to kisune, I have tried it on host, but I want to deploy it with docker, I don't find any docs about it, does kisune suppor docker deployment, or any plan for it?

**Comment by aumetra** [comment]
Kitsune has Docker support via Nix. We use that build system to build pretty much everything.

I added a GitHub Action to publish a container containing the main executable every day at 1AM as a sort of nightly build. The container doesn't contain the frontend though, I still need to figure out a setup that doesn't feel weirdly forced.

Container can be found here: https://github.com/kitsune-soc/kitsune/pkgs/container/kitsune

It's pushed to the GitHub Container Registry.

**Comment by aumetra** [comment]
For some reason the package was set to private, apologies for that. I set it to public.
